### ISSUE TITLE
Exposing backend data

### ISSUE THREAD

**Issue by rafaelstankiewicz** [MuddCreates/hyperschedule#209]
Hello,

Thanks for making hyperschedule! I'm a 5C student and I'm interested in making a program that can notify people when a seat in a class they're interested in is available. I'm not sure how I can access the backend data from your website, however. I'm resorting to webscraping right now but if there's an easier way please let me know! I'd be happy to contribute my code to your project as well if you're interested.

All the best,
Rafael Stankiewicz

**Comment by mia1024** [comment]
Hi there, the data is currently publicly accessible at `https://banana.hyperschedule.io/v4/sections/{term}`, where `{term}` is the term code such as `FA2023` or `SP2024`. You can find the data structure specification at [shared/api/v4/course.ts](https://github.com/hyperschedule/hyperschedule/blob/v2/shared/api/v4/course.ts#L162). However, I would caution you that when a class change from closed to reopened, the class becomes perm-only. So even if a seat becomes nominally available, it is unlikely that a student can register it immediately. They would still have to submit a perm and everything, which brings the question of how much benefit they can really get out of being notified the change of registration status of a class instead of submitting a perm as soon as they become interested in the class.

**Comment by kwshi** [comment]
On a not-directly-related note, usually when/if you're trying to reverse-engineer a website's API, before resorting to web-scraping you can often try using the "network inspector" devtool in your browser, which reveals all network requests being made by the app's client-side JS. For example, you can use it to see exactly how the current Hyperschedule frontend uses the banana.hyperschedule.io backend.

**Comment by rafaelstankiewicz** [comment]
Thank you both for the help!
