### ISSUE TITLE
Calendar Export Does Not Show Courses for the Last Day of the Section

### ISSUE THREAD

**Issue by CoolSpy3** [MuddCreates/hyperschedule#222]
The current section (FA2024) ends on Dec 13, 2024. However, in the current calendar export, courses which occur on that Friday are not shown. (The calendar stops after Thursday the 12th.) In order to maintain consistency with non-Friday classes, classes which occur on the last date of a section (in this case, Friday Dec 13) should be shown in the export.

**Comment by stuxf** [comment]
So where we obtain the final date is currently being sourced is via the portal API we use.

The json file with the data we fetch from portal:

https://github.com/hyperschedule/hyperschedule/blob/d8e5ed7f8df08e0417a88db26fb989077ea05306/data/FA2024/calendar-session.json#L5

So the date there is correct. 

Here is the actual code for where this gets put into the calendar, while the date is right here, the reason why the classes stop showing up is because we schedule it at the start of the day.

https://github.com/hyperschedule/hyperschedule/blob/d8e5ed7f8df08e0417a88db26fb989077ea05306/backend/src/routes/v4/calendar.ts#L196

I will write a PR to fix this later today, it should just be as simple as changing `T000000` to `T235959`, which I decided was better than incrementing the date string, in the event that the semester would end at the end of the month for some reason.
